#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PUTAirlinesMobile.Resource", IsApplication=true)]

namespace PUTAirlinesMobile
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int editTextBorder = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int logo = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int registerIcon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int userIcon = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060003
			public const int loginButton = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int loginProgressBar = 2131099653;
			
			// aapt resource value: 0x7f060001
			public const int loginText = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int passwordText = 2131099650;
			
			// aapt resource value: 0x7f060008
			public const int reLoad = 2131099656;
			
			// aapt resource value: 0x7f060006
			public const int registerButton = 2131099654;
			
			// aapt resource value: 0x7f060014
			public const int registerCity = 2131099668;
			
			// aapt resource value: 0x7f060017
			public const int registerClick = 2131099671;
			
			// aapt resource value: 0x7f06000b
			public const int registerLogin = 2131099659;
			
			// aapt resource value: 0x7f06000f
			public const int registerName = 2131099663;
			
			// aapt resource value: 0x7f060012
			public const int registerNationality = 2131099666;
			
			// aapt resource value: 0x7f060011
			public const int registerPassportNumber = 2131099665;
			
			// aapt resource value: 0x7f06000c
			public const int registerPassword = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int registerPassword2 = 2131099661;
			
			// aapt resource value: 0x7f060016
			public const int registerPostCode = 2131099670;
			
			// aapt resource value: 0x7f060018
			public const int registerProgressBar = 2131099672;
			
			// aapt resource value: 0x7f060015
			public const int registerStreet = 2131099669;
			
			// aapt resource value: 0x7f060010
			public const int registerSurname = 2131099664;
			
			// aapt resource value: 0x7f060004
			public const int rememberMeBox = 2131099652;
			
			// aapt resource value: 0x7f060009
			public const int scrollViewRegister = 2131099657;
			
			// aapt resource value: 0x7f060007
			public const int startImage = 2131099655;
			
			// aapt resource value: 0x7f060013
			public const int textView1 = 2131099667;
			
			// aapt resource value: 0x7f06000e
			public const int textView2 = 2131099662;
			
			// aapt resource value: 0x7f06000a
			public const int textView3 = 2131099658;
			
			// aapt resource value: 0x7f060000
			public const int userIconID = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int loginPage = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int MainActivity = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int panelPage = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int RegisterPage = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
