#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PUTAirlinesMobile.Resource", IsApplication=true)]

namespace PUTAirlinesMobile
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int blue = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int editTextBorder = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int logoHome = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int mojekonto_button = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int mojerezerwacje = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int one_order = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int registerIcon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int userIcon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int zamknij = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int zarezerwuj = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06002b
			public const int ButtonMojeKonto = 2131099691;
			
			// aapt resource value: 0x7f06002c
			public const int ButtonMojeRezerwacje = 2131099692;
			
			// aapt resource value: 0x7f06002d
			public const int ButtonZarezerwuj = 2131099693;
			
			// aapt resource value: 0x7f060022
			public const int DataHeader = 2131099682;
			
			// aapt resource value: 0x7f060011
			public const int DataRow = 2131099665;
			
			// aapt resource value: 0x7f06001f
			public const int Edytuj = 2131099679;
			
			// aapt resource value: 0x7f060046
			public const int FlyText = 2131099718;
			
			// aapt resource value: 0x7f06002f
			public const int LinearMyOrder = 2131099695;
			
			// aapt resource value: 0x7f060010
			public const int ProgressBar = 2131099664;
			
			// aapt resource value: 0x7f06002a
			public const int RelativeMenuLayout = 2131099690;
			
			// aapt resource value: 0x7f06004c
			public const int ResText = 2131099724;
			
			// aapt resource value: 0x7f060020
			public const int Usun = 2131099680;
			
			// aapt resource value: 0x7f06002e
			public const int WyjdzZAplikacji = 2131099694;
			
			// aapt resource value: 0x7f060033
			public const int actualPassword = 2131099699;
			
			// aapt resource value: 0x7f06005b
			public const int addLaggageButton = 2131099739;
			
			// aapt resource value: 0x7f06000e
			public const int changePasswordButton = 2131099662;
			
			// aapt resource value: 0x7f06005a
			public const int dangerousBox = 2131099738;
			
			// aapt resource value: 0x7f060049
			public const int date = 2131099721;
			
			// aapt resource value: 0x7f06000d
			public const int editButton = 2131099661;
			
			// aapt resource value: 0x7f060032
			public const int editTextPass = 2131099698;
			
			// aapt resource value: 0x7f060030
			public const int expandableListView1 = 2131099696;
			
			// aapt resource value: 0x7f06001a
			public const int h_dodlotu = 2131099674;
			
			// aapt resource value: 0x7f060018
			public const int h_dprzylotu = 2131099672;
			
			// aapt resource value: 0x7f060012
			public const int h_mwylotu = 2131099666;
			
			// aapt resource value: 0x7f06001c
			public const int h_o = 2131099676;
			
			// aapt resource value: 0x7f060016
			public const int hdrezerwacji = 2131099670;
			
			// aapt resource value: 0x7f060057
			public const int heightLuggage = 2131099735;
			
			// aapt resource value: 0x7f060014
			public const int hmprzylotu = 2131099668;
			
			// aapt resource value: 0x7f060021
			public const int imageView1 = 2131099681;
			
			// aapt resource value: 0x7f060003
			public const int individualNumber = 2131099651;
			
			// aapt resource value: 0x7f060055
			public const int laggTxt = 2131099733;
			
			// aapt resource value: 0x7f060031
			public const int layoutID = 2131099697;
			
			// aapt resource value: 0x7f060056
			public const int lengthLuggage = 2131099734;
			
			// aapt resource value: 0x7f06004f
			public const int leyouutLin = 2131099727;
			
			// aapt resource value: 0x7f060023
			public const int linearL = 2131099683;
			
			// aapt resource value: 0x7f06004d
			public const int listView = 2131099725;
			
			// aapt resource value: 0x7f060026
			public const int loginButton = 2131099686;
			
			// aapt resource value: 0x7f060028
			public const int loginProgressBar = 2131099688;
			
			// aapt resource value: 0x7f060001
			public const int loginText = 2131099649;
			
			// aapt resource value: 0x7f060053
			public const int name = 2131099731;
			
			// aapt resource value: 0x7f060052
			public const int nameLastTxt = 2131099730;
			
			// aapt resource value: 0x7f060034
			public const int newPassword1 = 2131099700;
			
			// aapt resource value: 0x7f060035
			public const int newPassword2 = 2131099701;
			
			// aapt resource value: 0x7f060025
			public const int passwordText = 2131099685;
			
			// aapt resource value: 0x7f060029
			public const int registerButton = 2131099689;
			
			// aapt resource value: 0x7f060040
			public const int registerCity = 2131099712;
			
			// aapt resource value: 0x7f060043
			public const int registerClick = 2131099715;
			
			// aapt resource value: 0x7f060039
			public const int registerLogin = 2131099705;
			
			// aapt resource value: 0x7f06003c
			public const int registerName = 2131099708;
			
			// aapt resource value: 0x7f06003f
			public const int registerNationality = 2131099711;
			
			// aapt resource value: 0x7f06003e
			public const int registerPassportNumber = 2131099710;
			
			// aapt resource value: 0x7f06003a
			public const int registerPassword = 2131099706;
			
			// aapt resource value: 0x7f06003b
			public const int registerPassword2 = 2131099707;
			
			// aapt resource value: 0x7f060042
			public const int registerPostCode = 2131099714;
			
			// aapt resource value: 0x7f060044
			public const int registerProgressBar = 2131099716;
			
			// aapt resource value: 0x7f060041
			public const int registerStreet = 2131099713;
			
			// aapt resource value: 0x7f06003d
			public const int registerSurname = 2131099709;
			
			// aapt resource value: 0x7f060045
			public const int relLayout = 2131099717;
			
			// aapt resource value: 0x7f06001e
			public const int relativeLayout1 = 2131099678;
			
			// aapt resource value: 0x7f060027
			public const int rememberMeBox = 2131099687;
			
			// aapt resource value: 0x7f060036
			public const int saveChange = 2131099702;
			
			// aapt resource value: 0x7f060000
			public const int scroll = 2131099648;
			
			// aapt resource value: 0x7f06004e
			public const int scrollViewLay = 2131099726;
			
			// aapt resource value: 0x7f060037
			public const int scrollViewRegister = 2131099703;
			
			// aapt resource value: 0x7f06004b
			public const int searchFlys = 2131099723;
			
			// aapt resource value: 0x7f060047
			public const int spinner1 = 2131099719;
			
			// aapt resource value: 0x7f060048
			public const int spinner2 = 2131099720;
			
			// aapt resource value: 0x7f06004a
			public const int startPlace = 2131099722;
			
			// aapt resource value: 0x7f060054
			public const int surName = 2131099732;
			
			// aapt resource value: 0x7f06001b
			public const int t_dodlutu = 2131099675;
			
			// aapt resource value: 0x7f060019
			public const int t_dprzylotu = 2131099673;
			
			// aapt resource value: 0x7f060017
			public const int t_drezerwacji = 2131099671;
			
			// aapt resource value: 0x7f060015
			public const int t_mprzylotu = 2131099669;
			
			// aapt resource value: 0x7f060013
			public const int t_mwylotu = 2131099667;
			
			// aapt resource value: 0x7f06001d
			public const int t_o = 2131099677;
			
			// aapt resource value: 0x7f060007
			public const int textView1 = 2131099655;
			
			// aapt resource value: 0x7f060004
			public const int textView2 = 2131099652;
			
			// aapt resource value: 0x7f060038
			public const int textView3 = 2131099704;
			
			// aapt resource value: 0x7f060002
			public const int textView4 = 2131099650;
			
			// aapt resource value: 0x7f06000f
			public const int updateButton = 2131099663;
			
			// aapt resource value: 0x7f060024
			public const int userIconID = 2131099684;
			
			// aapt resource value: 0x7f060051
			public const int valueSpinner = 2131099729;
			
			// aapt resource value: 0x7f060050
			public const int valueTxt = 2131099728;
			
			// aapt resource value: 0x7f060059
			public const int weightLuggage = 2131099737;
			
			// aapt resource value: 0x7f060058
			public const int widthLuggage = 2131099736;
			
			// aapt resource value: 0x7f06000a
			public const int yourCity = 2131099658;
			
			// aapt resource value: 0x7f060005
			public const int yourName = 2131099653;
			
			// aapt resource value: 0x7f06000c
			public const int yourNationality = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int yourPassportNumber = 2131099659;
			
			// aapt resource value: 0x7f060009
			public const int yourPostCode = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int yourStreet = 2131099656;
			
			// aapt resource value: 0x7f060006
			public const int yourSurname = 2131099654;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AccountPage = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DataListItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Home = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ListGroup = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int loginPage = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int MenuLayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int MyOrderLayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int PasswordChange = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int RegisterPage = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int ReserveTickets = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int ReserveTickets_2 = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int spinner_layout = 2130903051;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
